[package]
name = "telegram-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = { workspace = true }
graphql_client = { workspace = true }
reqwest = { workspace = true }
schematic = { workspace = true }
serde = { workspace = true }
teloxide = { workspace = true }
tokio = { workspace = true }
