//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod music_link;
pub mod telegram_bot_channel;
pub mod telegram_bot_music_share;
pub mod telegram_bot_music_share_reaction;
pub mod telegram_bot_user;
