//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub use super::music_link::Entity as MusicLink;
pub use super::telegram_bot_channel::Entity as TelegramBotChannel;
pub use super::telegram_bot_user::Entity as TelegramBotUser;
