//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "telegram_bot_user")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub telegram_user_id: i64,
    pub assigned_emoji: String,
    pub created_at: DateTimeUtc,
    pub telegram_bot_channel_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::telegram_bot_channel::Entity",
        from = "Column::TelegramBotChannelId",
        to = "super::telegram_bot_channel::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    TelegramBotChannel,
}

impl Related<super::telegram_bot_channel::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramBotChannel.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
