//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "telegram_bot_channel")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub created_at: DateTimeUtc,
    #[sea_orm(unique)]
    pub telegram_channel_id: i64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::telegram_bot_user::Entity")]
    TelegramBotUser,
}

impl Related<super::telegram_bot_user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TelegramBotUser.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
