name: Build and Publish Docker Image

on:
  push:
    branches: ["main"]
    tags:
      - "*-?v[0-9]+*"
  pull_request:
    branches: ["main"]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  pre-workflow-checks:
    runs-on: ubuntu-latest
    outputs:
      should-run: ${{ steps.set_outputs.outputs.should-run }}
      should-release: ${{ steps.set_outputs.outputs.should-release }}
    steps:
      - name: Set outputs
        id: set_outputs
        uses: actions/github-script@v7
        with:
          script: |
            let shouldRun = 'false';
            if (context.eventName === "push") {
              shouldRun = 'true';
            } else if (context.eventName === "pull_request") {
              const commitMsg = await github.rest.repos.getCommit({
                repo: context.repo.repo,
                owner: context.repo.owner,
                ref: context.payload.pull_request.head.sha
              }).then(commit => commit.data.commit.message);
              if (commitMsg.includes("Run CI")) {
                shouldRun = 'true';
              }
            }
            core.setOutput('should-run', shouldRun);

            const shouldRelease = (context.eventName === "push" && context.ref.startsWith("refs/tags/")) ? 'true' : 'false';
            core.setOutput('should-release', shouldRelease);

  build-and-push:
    needs: pre-workflow-checks
    if: needs.pre-workflow-checks.outputs.should-run == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha
            type=ref,event=pr
            type=raw,value=develop,enable={{is_default_branch}}
            type=raw,value=latest,enable=${{ needs.pre-workflow-checks.outputs.should-release == 'true' }}
            type=semver,pattern=v{{major}},enable=${{ needs.pre-workflow-checks.outputs.should-release == 'true' }}
            type=semver,pattern=v{{version}},enable=${{ needs.pre-workflow-checks.outputs.should-release == 'true' }}
            type=semver,pattern=v{{major}}.{{minor}},enable=${{ needs.pre-workflow-checks.outputs.should-release == 'true' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
